#!/bin/sh

# Programs
export EDITOR=nvim
export TERMINAL=alacritty
export BROWSER=firefox
export TERM=xterm-256color

export PATH="$HOME/.local/bin:$PATH"
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

alias cp='cp -v'
alias mv='mv -v'
alias rm='rm -v'

alias htop='htop --tree'
alias ls='ls --color=auto'
alias lsd='ls --color=auto -al'
alias lsl='ls --color=auto -l'

alias rp='cd "$(find ~/p -name .git -type d -prune | fzf --height=8 --layout=reverse || echo $HOME/p)/.."'
alias find-node-modules='find . -name 'node_modules' -prune'
alias myip='curl ifconfig.co/'
alias lg='lazygit'
alias vim='nvim'
alias todo='nvim ~/.local/share/todo'
alias du='du -h'
alias diff='diff --color=auto'
alias k='kubectl'


export FZF_DEFAULT_OPS='--layout=reverse -i'
export PASSWORD_STORE_DIR="$HOME/.local/share/password-store"
export NVM_DIR="$HOME/.config/nvm"
export NPM_CONFIG_USERCONFIG="$HOME/.config/npm/npmrc"
export PNPM_HOME="$HOME/.local/share/pnpm"
export CARGO_HOME="$HOME/.local/share/cargo"
export MOZ_ENABLE_WAYLAND=1
